// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// inverseScHazCppTryTimeVar
double inverseScHazCppTryTimeVar(double p, double t, double lower, double upper, double t_prime, NumericVector eta, NumericVector nu, NumericVector phi, NumericVector phi_prime, NumericVector at_risk, double tol, int max_iter);
RcppExport SEXP _simevent_inverseScHazCppTryTimeVar(SEXP pSEXP, SEXP tSEXP, SEXP lowerSEXP, SEXP upperSEXP, SEXP t_primeSEXP, SEXP etaSEXP, SEXP nuSEXP, SEXP phiSEXP, SEXP phi_primeSEXP, SEXP at_riskSEXP, SEXP tolSEXP, SEXP max_iterSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type p(pSEXP);
    Rcpp::traits::input_parameter< double >::type t(tSEXP);
    Rcpp::traits::input_parameter< double >::type lower(lowerSEXP);
    Rcpp::traits::input_parameter< double >::type upper(upperSEXP);
    Rcpp::traits::input_parameter< double >::type t_prime(t_primeSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type eta(etaSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type nu(nuSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type phi(phiSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type phi_prime(phi_primeSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type at_risk(at_riskSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    Rcpp::traits::input_parameter< int >::type max_iter(max_iterSEXP);
    rcpp_result_gen = Rcpp::wrap(inverseScHazCppTryTimeVar(p, t, lower, upper, t_prime, eta, nu, phi, phi_prime, at_risk, tol, max_iter));
    return rcpp_result_gen;
END_RCPP
}
// inverseScHazCpp
double inverseScHazCpp(double p, double t, double lower, double upper, NumericVector eta, NumericVector nu, NumericVector phi, NumericVector at_risk, double tol, int max_iter);
RcppExport SEXP _simevent_inverseScHazCpp(SEXP pSEXP, SEXP tSEXP, SEXP lowerSEXP, SEXP upperSEXP, SEXP etaSEXP, SEXP nuSEXP, SEXP phiSEXP, SEXP at_riskSEXP, SEXP tolSEXP, SEXP max_iterSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type p(pSEXP);
    Rcpp::traits::input_parameter< double >::type t(tSEXP);
    Rcpp::traits::input_parameter< double >::type lower(lowerSEXP);
    Rcpp::traits::input_parameter< double >::type upper(upperSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type eta(etaSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type nu(nuSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type phi(phiSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type at_risk(at_riskSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    Rcpp::traits::input_parameter< int >::type max_iter(max_iterSEXP);
    rcpp_result_gen = Rcpp::wrap(inverseScHazCpp(p, t, lower, upper, eta, nu, phi, at_risk, tol, max_iter));
    return rcpp_result_gen;
END_RCPP
}
// sampleEventsCpp
IntegerVector sampleEventsCpp(NumericMatrix probs);
RcppExport SEXP _simevent_sampleEventsCpp(SEXP probsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type probs(probsSEXP);
    rcpp_result_gen = Rcpp::wrap(sampleEventsCpp(probs));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_simevent_inverseScHazCppTryTimeVar", (DL_FUNC) &_simevent_inverseScHazCppTryTimeVar, 12},
    {"_simevent_inverseScHazCpp", (DL_FUNC) &_simevent_inverseScHazCpp, 10},
    {"_simevent_sampleEventsCpp", (DL_FUNC) &_simevent_sampleEventsCpp, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_simevent(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
