# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

inverseScHazCpp <- function(p, t, lower, upper, eta, nu, phi, at_risk, tol = 1e-9, max_iter = 100L) {
    .Call(`_simevent_inverseScHazCpp`, p, t, lower, upper, eta, nu, phi, at_risk, tol, max_iter)
}

sampleEvents <- function(probs) {
    .Call(`_simevent_sampleEvents`, probs)
}

